package com.example.andreromano.coolweather

object CountryUtils {

    fun iso2ToCountryName(iso2: String): String? = countryList[iso2]

    private val countryList = mapOf(
        "AF" to "Afghanistan",
        "AL" to "Albania",
        "DZ" to "Algeria",
        "AS" to "American Samoa",
        "AD" to "Andorra",
        "AO" to "Angola",
        "AI" to "Anguilla",
        "AQ" to "Antarctica",
        "AG" to "Antigua and Barbuda",
        "AR" to "Argentina",
        "AM" to "Armenia",
        "AW" to "Aruba",
        "AC" to "Ascension",
        "AU" to "Australia",
        "AT" to "Austria",
        "AZ" to "Azerbaijan",
        "BS" to "Bahamas",
        "BH" to "Bahrain",
        "BD" to "Bangladesh",
        "BB" to "Barbados",
        "BY" to "Belarus",
        "BE" to "Belgium",
        "BZ" to "Belize",
        "BJ" to "Benin",
        "BM" to "Bermuda",
        "BT" to "Bhutan",
        "BO" to "Bolivia",
        "BA" to "Bosnia and Herzegovina",
        "BW" to "Botswana",
        "BR" to "Brazil",
        "IO" to "British Indian Ocean Territory",
        "VG" to "British Virgin Islands",
        "BN" to "Brunei",
        "BG" to "Bulgaria",
        "BF" to "Burkina Faso",
        "BI" to "Burundi",
        "KH" to "Cambodia",
        "CM" to "Cameroon",
        "CA" to "Canada",
        "CV" to "Cape Verde",
        "KY" to "Cayman Islands",
        "CF" to "Central African Republic",
        "TD" to "Chad",
        "CL" to "Chile",
        "CN" to "China",
        "CC" to "Cocos Islands",
        "CO" to "Colombia",
        "KM" to "Comoros",
        "CK" to "Cook Islands",
        "CR" to "Costa Rica",
        "HR" to "Croatia",
        "CU" to "Cuba",
        "CW" to "Curacao",
        "CY" to "Cyprus",
        "CZ" to "Czech Republic",
        "CD" to "Democratic Republic of the Congo",
        "DK" to "Denmark",
        "DJ" to "Djibouti",
        "DM" to "Dominica",
        "DO" to "Dominican Republic",
        "DO" to "Dominican Republic",
        "DO" to "Dominican Republic",
        "TL" to "East Timor",
        "EC" to "Ecuador",
        "EG" to "Egypt",
        "SV" to "El Salvador",
        "GQ" to "Equatorial Guinea",
        "ER" to "Eritrea",
        "EE" to "Estonia",
        "ET" to "Ethiopia",
        "FK" to "Falkland Islands",
        "FO" to "Faroe Islands",
        "FJ" to "Fiji",
        "FI" to "Finland",
        "FR" to "France",
        "PF" to "French Polynesia",
        "GA" to "Gabon",
        "GM" to "Gambia",
        "GE" to "Georgia",
        "DE" to "Germany",
        "GH" to "Ghana",
        "GI" to "Gibraltar",
        "GR" to "Greece",
        "GL" to "Greenland",
        "GD" to "Grenada",
        "GP" to "Guadeloupe",
        "GU" to "Guam",
        "GT" to "Guatemala",
        "GF" to "French Guiana",
        "GG" to "Guernsey",
        "GN" to "Guinea",
        "GW" to "Guinea-Bissau",
        "GY" to "Guyana",
        "HT" to "Haiti",
        "HN" to "Honduras",
        "HK" to "Hong Kong",
        "HU" to "Hungary",
        "IS" to "Iceland",
        "IN" to "India",
        "ID" to "Indonesia",
        "IR" to "Iran",
        "IQ" to "Iraq",
        "IE" to "Ireland",
        "IM" to "Isle of Man",
        "IL" to "Israel",
        "IT" to "Italy",
        "CI" to "Ivory Coast",
        "JM" to "Jamaica",
        "JP" to "Japan",
        "JE" to "Jersey",
        "JO" to "Jordan",
        "KZ" to "Kazakhstan",
        "KE" to "Kenya",
        "KI" to "Kiribati",
        "XK" to "Kosovo",
        "KW" to "Kuwait",
        "KG" to "Kyrgyzstan",
        "LA" to "Laos",
        "LV" to "Latvia",
        "LB" to "Lebanon",
        "LS" to "Lesotho",
        "LR" to "Liberia",
        "LY" to "Libya",
        "LI" to "Liechtenstein",
        "LT" to "Lithuania",
        "LU" to "Luxembourg",
        "MO" to "Macao",
        "MK" to "Macedonia",
        "MG" to "Madagascar",
        "MW" to "Malawi",
        "MY" to "Malaysia",
        "MV" to "Maldives",
        "ML" to "Mali",
        "MT" to "Malta",
        "MH" to "Marshall Islands",
        "FR" to "Martinique",
        "MR" to "Mauritania",
        "MU" to "Mauritius",
        "YT" to "Mayotte",
        "MX" to "Mexico",
        "FM" to "Micronesia",
        "MD" to "Moldova",
        "MC" to "Monaco",
        "MN" to "Mongolia",
        "ME" to "Montenegro",
        "MS" to "Montserrat",
        "MA" to "Morocco",
        "MZ" to "Mozambique",
        "MM" to "Myanmar",
        "NA" to "Namibia",
        "NR" to "Nauru",
        "NP" to "Nepal",
        "NL" to "Netherlands",
        "AN" to "Netherlands Antilles",
        "NC" to "New Caledonia",
        "NZ" to "New Zealand",
        "NI" to "Nicaragua",
        "NE" to "Niger",
        "NG" to "Nigeria",
        "NU" to "Niue",
        "NF" to "Norfolk",
        "KP" to "North Korea",
        "MP" to "Northern Mariana Islands",
        "NO" to "Norway",
        "OM" to "Oman",
        "PK" to "Pakistan",
        "PW" to "Palau",
        "PS" to "Palestine",
        "PA" to "Panama",
        "PG" to "Papua New Guinea",
        "PY" to "Paraguay",
        "PE" to "Peru",
        "PH" to "Philippines",
        "PN" to "Pitcairn",
        "PL" to "Poland",
        "PT" to "Portugal",
        "PR" to "Puerto Rico",
        "PR" to "Puerto Rico",
        "QA" to "Qatar",
        "CG" to "Republic of the Congo",
        "RE" to "Reunion",
        "RO" to "Romania",
        "RU" to "Russia",
        "RW" to "Rwanda",
        "BL" to "Saint Barthelemy",
        "SH" to "Saint Helena",
        "KN" to "Saint Kitts and Nevis",
        "LC" to "Saint Lucia",
        "MF" to "Saint Martin",
        "PM" to "Saint Pierre and Miquelon",
        "VC" to "Saint Vincent and the Grenadines",
        "WS" to "Samoa",
        "SM" to "San Marino",
        "ST" to "Sao Tome and Principe",
        "SA" to "Saudi Arabia",
        "SN" to "Senegal",
        "RS" to "Serbia",
        "SC" to "Seychelles",
        "SL" to "Sierra Leone",
        "SG" to "Singapore",
        "SX" to "Sint Maarten",
        "SK" to "Slovakia",
        "SI" to "Slovenia",
        "SB" to "Solomon Islands",
        "SO" to "Somalia",
        "ZA" to "South Africa",
        "KR" to "South Korea",
        "SS" to "South Sudan",
        "ES" to "Spain",
        "LK" to "Sri Lanka",
        "SD" to "Sudan",
        "SR" to "Suriname",
        "SJ" to "Svalbard and Jan Mayen",
        "SZ" to "Swaziland",
        "SE" to "Sweden",
        "CH" to "Switzerland",
        "SY" to "Syria",
        "TW" to "Taiwan",
        "TJ" to "Tajikistan",
        "TZ" to "Tanzania",
        "TH" to "Thailand",
        "TG" to "Togo",
        "TK" to "Tokelau",
        "TO" to "Tonga",
        "TT" to "Trinidad and Tobago",
        "TN" to "Tunisia",
        "TR" to "Turkey",
        "TM" to "Turkmenistan",
        "TC" to "Turks and Caicos Islands",
        "TV" to "Tuvalu",
        "VI" to "U.S. Virgin Islands",
        "UG" to "Uganda",
        "UA" to "Ukraine",
        "AE" to "United Arab Emirates",
        "UK" to "United Kingdom",
        "US" to "United States",
        "UY" to "Uruguay",
        "UZ" to "Uzbekistan",
        "VU" to "Vanuatu",
        "VA" to "Vatican",
        "VE" to "Venezuela",
        "VN" to "Vietnam",
        "WF" to "Wallis and Futuna",
        "EH" to "Western Sahara",
        "YE" to "Yemen",
        "ZM" to "Zambia",
        "ZW" to "Zimbabwe"
    )

}